package com.kadiri.elkitabi.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// ═══ KARANLIK TEMA (OLED OPTİMİZE — VARSAYILAN) ═══
val PrimaryDark            = Color(0xFF5FD99A)
val OnPrimaryDark          = Color(0xFF003822)
val PrimaryContainerDark   = Color(0xFF0F3D2C)
val SecondaryDark          = Color(0xFFF0C040)
val OnSecondaryDark        = Color(0xFF3A2800)
val SecondaryContainerDark = Color(0xFF5C4200)
val TertiaryDark           = Color(0xFFD8A8FF)
val OnTertiaryDark         = Color(0xFF3D0060)
val TertiaryContainerDark  = Color(0xFF560087)
val BackgroundDark         = Color(0xFF080A09)
val OnBackgroundDark       = Color(0xFFE0E8E3)
val SurfaceDark            = Color(0xFF0D100E)
val OnSurfaceDark          = Color(0xFFE0E8E3)
val SurfaceVariantDark     = Color(0xFF1E2520)
val OnSurfaceVariantDark   = Color(0xFFBFCBC4)
val OutlineDark            = Color(0xFF8FAF97)
val OutlineVariantDark     = Color(0xFF3E4D45)
val ErrorDark              = Color(0xFFFFB4AB)
val OnErrorDark            = Color(0xFF690005)
val ErrorContainerDark     = Color(0xFF93000A)

// ═══ IŞIK TEMA ═══
val PrimaryLight            = Color(0xFF1B4D3E)
val OnPrimaryLight          = Color(0xFFFFFFFF)
val PrimaryContainerLight   = Color(0xFFC8F0DC)
val OnPrimaryContainerLight = Color(0xFF002114)
val SecondaryLight          = Color(0xFF8B6914)
val OnSecondaryLight        = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFF5E6B3)
val TertiaryLight           = Color(0xFF5C3A78)
val OnTertiaryLight         = Color(0xFFFFFFFF)
val TertiaryContainerLight  = Color(0xFFEDD8FF)
val BackgroundLight         = Color(0xFFFDFAF4)
val OnBackgroundLight       = Color(0xFF1A1C1A)
val SurfaceLight            = Color(0xFFF7F3EC)
val OnSurfaceLight          = Color(0xFF1A1C1A)
val SurfaceVariantLight     = Color(0xFFEDE8DF)
val OnSurfaceVariantLight   = Color(0xFF44483F)
val OutlineLight            = Color(0xFF74796F)
val OutlineVariantLight     = Color(0xFFC4C8BD)
val ErrorLight              = Color(0xFFBA1A1A)
val OnErrorLight            = Color(0xFFFFFFFF)
val ErrorContainerLight     = Color(0xFFFFDAD6)

// ═══ ÖZEL RENK TOKENLERİ ═══
val GoldAccent              = Color(0xFFD4AF37)
val GoldAccentLight         = Color(0xFFFFD700)
val ArabesqueGold           = Color(0xFFB8961E)
val IslamicGreen            = Color(0xFF2E7D52)
val MysticPurple            = Color(0xFF6A3D9A)
val OLEDBlack               = Color(0xFF000000)
val WarmAmber               = Color(0xFFFF8F00)

// ═══ GRADYANLAR ═══
val PrimaryGradient         = listOf(Color(0xFF0F3D2C), Color(0xFF1B4D3E))
val GoldGradient            = listOf(Color(0xFFB8961E), Color(0xFFFFD700))
val SpiritualGradient       = listOf(Color(0xFF1B4D3E), Color(0xFF5C3A78))
val ZikirBgGradient         = listOf(Color(0xFF080A09), Color(0xFF0D1F18))
val SunriseGradient         = listOf(Color(0xFF3D0060), Color(0xFF8B6914), Color(0xFF5FD99A))
